src/main/java/frc/robot/constants/LiftConstants.java, src/main/java/frc/robot/subsystems/Lift.java
=> first pass lift subsystem skeleton

src/main/java/frc/robot/constants/AcquisitionConstants.java, src/main/java/frc/robot/subsystems/Acquisition.java
=> finished issue 1

src/main/java/frc/robot/constants/StorageConstants.java, src/main/java/frc/robot/subsystems/Storage.java
finished the issue for storage subsystem skeleton
Closes #4
=> finished the issue for storage subsystem skeleton

src/main/java/frc/robot/commands/LiftDepressCommand.java, src/main/java/frc/robot/commands/LiftElevateCommand.java, src/main/java/frc/robot/commands/LiftExtendCommand.java, src/main/java/frc/robot/subsystems/Lift.java
created two command skeletons, one to depress the lift elevator and one to raise it.
=> TWO lift commands (one to depress one to elevate)

src/main/java/frc/robot/commands/StorageRunCommand.java, src/main/java/frc/robot/constants/StorageConstants.java, src/main/java/frc/robot/subsystems/Storage.java
Closes #13
I made the skeleton for the storage run command
=> i did theStorage Run Command Skeleton

.vscode/settings.json, src/main/java/frc/robot/commands/LiftDepressCommand.java, src/main/java/frc/robot/commands/ScoreNoteCommand.java, src/main/java/frc/robot/constants/ScoringConstants.java, src/main/java/frc/robot/subsystems/Scoring.java
fulfilled issue parameters according to new design information
=> updated scoring subsystem + command :D

src/main/java/frc/robot/subsystems/Storage.java
Added documentation to the Storage subsystem.
=> Storage comments

src/main/java/frc/robot/subsystems/Acquisition.java
Added documentation to the Acquisition subsystem.
=> added documentation to Acquisition

src/main/java/frc/robot/subsystems/Lift.java
Added documentation to the Lift subsystem.
=> added doucmentation to the lift subsystem

src/main/java/frc/robot/commands/ScoreNoteCommand.java, src/main/java/frc/robot/subsystems/Scoring.java
Added javadocs to scoring subsystem
=> Scoring javadocs for Scoring subsystem and scoreNoteCommand

.github/pull_request_template.md, src/main/java/frc/robot/commands/AcquireCommand.java, src/main/java/frc/robot/commands/DropNoteCommand.java, src/main/java/frc/robot/commands/ScoreNoreAmpCommand.java, src/main/java/frc/robot/commands/ScoringPositionCommand.java, src/main/java/frc/robot/commands/ShootNoteCommand.java, src/main/java/frc/robot/commands/StorageRunCommand.java, src/main/java/frc/robot/commands/SushiForwardCommand.java, src/main/java/frc/robot/commands/TransitionRunCommand.java, src/main/java/frc/robot/commands/UnacquireCommand.java, src/main/java/frc/robot/constants/AcquisitionConstants.java, src/main/java/frc/robot/constants/LiftConstants.java, src/main/java/frc/robot/constants/ScoringConstants.java, src/main/java/frc/robot/constants/StorageConstants.java, src/main/java/frc/robot/subsystems/Acquisition.java, src/main/java/frc/robot/subsystems/Lift.java, src/main/java/frc/robot/subsystems/Scoring.java, src/main/java/frc/robot/subsystems/Storage.java
=> 57 update all the subsystems and commands

.vscode/launch.json, src/main/java/frc/robot/autons/ScoreInAmp.java, src/main/java/frc/robot/commands/DriveVisionCommand.java
=> Score in Amp Auton

src/main/java/frc/robot/commands/FullAcquireSequenceCommand.java
=> made command

src/main/java/frc/robot/constants/StorageConstants.java, src/main/java/frc/robot/subsystems/Storage.java
=> renamed symbols

src/main/java/frc/robot/DriverJoystick.java, src/main/java/frc/robot/OperatorJoystick.java
=> joystick code updated to current commands

src/main/java/frc/robot/commands/ScoreNoteAmpCommand.java
<!-- Uncomment the line below and change the issue number to mach the one ths PR is for --
Closes #86
fixed note amp
=> fixrf maybe score note amp

src/main/java/frc/robot/subsystems/Scoring.java
=> changed roller type to CANSparkFlex

src/main/java/frc/robot/autons/Paths.java, src/main/java/frc/robot/autons/ScoreInAmp.java
=> Created a New File Containing all of Our Paths/Trajectories

src/main/java/frc/robot/constants/AcquisitionConstants.java, src/main/java/frc/robot/constants/DriveConstants.java, src/main/java/frc/robot/constants/LiftConstants.java, src/main/java/frc/robot/constants/ScoringConstants.java, src/main/java/frc/robot/constants/StorageConstants.java
=> most ports added

src/main/java/frc/robot/DriverJoystick.java, src/main/java/frc/robot/commands/LeftLiftDownCommand.java, src/main/java/frc/robot/commands/LeftLiftUpCommand.java, src/main/java/frc/robot/commands/RightLiftDownCommand.java, src/main/java/frc/robot/commands/RightLiftUpCommand.java, src/main/java/frc/robot/subsystems/Lift.java
=> changed the lift to be both sides

src/main/java/frc/robot/constants/ScoringElevatorConstants.java
=> made setpoint for elevator so it goes to correct height

src/main/java/frc/robot/constants/ScoringElevatorConstants.java
=> Changed setpoint for trap from 14 to 15

src/main/java/frc/robot/OperatorJoystick.java, src/main/java/frc/robot/commands/AcquisitionRunCommand.java, src/main/java/frc/robot/commands/FullAcquireCommand.java, src/main/java/frc/robot/commands/ScoringElevatorPositionCommand.java, src/main/java/frc/robot/commands/StorageRunCommand.java, src/main/java/frc/robot/commands/TransitionRunCommand.java, src/main/java/frc/robot/commands/UnacquireCommand.java, src/main/java/frc/robot/subsystems/Acquisition.java, src/main/java/frc/robot/subsystems/ScoringElevator.java
=> fixed acuqire all command

src/main/java/frc/robot/OperatorJoystick.java, src/main/java/frc/robot/commands/DrawbridgeDownCommand.java, src/main/java/frc/robot/commands/DrawbridgeUpCommand.java, src/main/java/frc/robot/constants/DrawbridgeConstants.java, src/main/java/frc/robot/subsystems/Drawbridge.java
=> made the drawbridge code for trap scoring

src/main/java/frc/robot/subsystems/Lift.java
=> Fixed return statement

src/main/java/frc/robot/Robot.java, src/main/java/frc/robot/commands/LiftUpCommand.java, src/main/java/frc/robot/subsystems/Lift.java
=> Make lift go down at start of match

src/main/java/frc/robot/Robot.java, src/main/java/frc/robot/autons/ScoreInAmpWait.java, src/main/java/frc/robot/subsystems/Dashboard.java, src/main/java/frc/robot/subsystems/DriveTrain.java, src/main/java/frc/robot/subsystems/Lift.java
=> deleted unused imports

src/main/deploy/pathplanner/paths/From amp to midline acquire.path, src/main/deploy/pathplanner/paths/From midline note to amp.path, src/main/java/frc/robot/commands/ShootPasserCommand.java, src/main/java/frc/robot/constants/DrawbridgeConstants.java, src/main/java/frc/robot/constants/NeoMotorConstants.java, src/main/java/frc/robot/constants/ScoringElevatorConstants.java
=> updates from drive practice

src/main/java/frc/robot/constants/ScoringConstants.java
=> Ohio champs
